\documentclass[12pt,]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
    \setmainfont[]{Times New Roman}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=2.54cm]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdftitle={Examining the Hydrologic Properties of the Missouri River Basin},
            pdfauthor={Rachel Bash, Keqi He, Caroline Watson, and Haoyu Zhang},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{longtable,booktabs}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\providecommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}

  \title{Examining the Hydrologic Properties of the Missouri River Basin}
    \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
  \subtitle{\url{https://github.com/cwatson1013/Hydrologic_Data_Analysis_Final_Proj}}
  \author{Rachel Bash, Keqi He, Caroline Watson, and Haoyu Zhang}
    \preauthor{\centering\large\emph}
  \postauthor{\par}
    \date{}
    \predate{}\postdate{}
  
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}

\usepackage{float}

\begin{document}
\maketitle

\newpage

\hypertarget{rationale-and-research-questions}{%
\section{Rationale and Research
Questions}\label{rationale-and-research-questions}}

The Missouri River is the largest river in North America (2,540 miles)
and has the second largest watershed (529,000 mi\textsuperscript{2}/339
acres, U.S.-Canada, (Kammerer 1990)). Its watershed covers portions of
ten states, which account for approximately one-sixth of the continental
United States, as well as a small part of Canada (Engineers Missouri
River Basin Water Management Division 2018). The headwater is located in
the Bitterroot Mountains River of northwestern Wyoming and southwestern
Montana (Council 2002). Demands for managing the river for the benefit
of human livelihood has resulted in drastic modification in the river
and the floodplains. Numerous reservoirs and dams have been constructed,
of which six major dams were built on the mainstream(Council 2002). Now,
the river is used intensively in multiple ways, including municipal,
agricultural, hydropower, recreation, flood control etc. (Reclamation
2016b).

Within the 328 million acres of the basin's total area in the United
States, 64.2\% (218 acres) are related to agricultural uses, while the
rest dedicated for recreation, fish and wildlife, and urban (Reclamation
2016b, @usace2018). 37.1\% of the total basin area is pasture and range
grassland primarily for grazing, and cropland consists of almost 92
million acres (Engineers Missouri River Basin Water Management Division
2018). As of 2012, irrigated land comprises 14.2 million acres, and
required a delivery of about 13 million acre-feet of surface water
annually (Engineers Missouri River Basin Water Management Division
2018). Wetlands and Water bodies, on the other hand, cover 3.7 and 1.8
million acres, respectively (Engineers Missouri River Basin Water
Management Division 2018). In spite of the low proportion of water areas
(2.3\%), they are the pivotal foundation for agricultural or other
usages, and thus critical to the whole region's economy.

Along with the agricultural, urban, and industrial development in the
region is nutrient loading and enrichment in water bodies, especially
for nitrogen (N) and phosphorus (P). Agricultural input through
fertilizer is the predominant anthropogenic source for nutrient in water
bodies in the whole basin (Council 2002). Regardless of the major
anthropogenic source, nutrient enrichment is considered nationally as
one of the leading factors for water quality impairment. According to
USEPA 303(d) lists, more than 160 stream reaches, lakes, or reservoirs
were reported by USEPA to suffer nutrient-related impairment in 2006
(Council 2002).

In addition to change in nutrient concentration, discharge appears to be
highly variable in the basin, and both severe drought and flooding
events occurred in the basin in the past. For example, in the spring and
summer of 2011, an unprecedented flooding event caused over \$2 billion
damage and 5 fatalities, leading to FEMA disaster declaration made in
all states along the Missouri River (Oceanic and Administration 2012).
During the flooding event, around 11,000 people evacuated Minot, North
Dakota owing to high water level in Souris River, which flooded 4,000
homes (Oceanic and Administration 2012). In 2012, a drought even struck
the Central Great Plain, including the basin, and inflicted at least
\$12 billion of loss before July, 2012 (Force 2013). Recently, another
flooding event occurred in the spring of 2019.

Given all the background information above, we would like to know the
current state of Missouri River and its tributaries, with a focus on the
changing patterns in discharge and nutrient levels. Water bodies along
the downstream are more likely to be impaired by nutrients accumulated
from the upstream, and more croplands and pastures which can further
load nutrients into streams are distributed in the lower basins
(\autoref{fig:cropland}). Therefore, in the present project, study sites
were concentrated in the southeast of the whole Missouri Basin. By
analyzing data retrieved from these sites, we first revealed the general
yearly discharge pattern and changes in variability over years. Then we
investigated how the dramatic change in discharge (i.e.~water quantity)
could potentially interact with nutrient enrichment (i.e.~water
quality). We examined a few specific flooding and drought events, during
which changes in both water quality and quantity were well recorded, so
that we could make inference on the interplay between quantity and
quality. The effect of population on nutrient enrichment was also
examined to illustrate potential non-agricultural impact from human
activities. Finally, based on the pattern in the past and the best model
we could fit, we attempted to predict the likely future conditions and
trends in the Missouri River Basin. Our research questions and
acccompanying hypotheses are below:

\begin{figure}[H]
\includegraphics[width=\maxwidth]{../Figures/cropland3} \caption{\label{fig:cropland} Map of agricultural lands and impaired waters in the Missouri River Basin. Row and Close Grain Crop Cultural Formation shown by tan-colored areas, pasture and hay field shown by yellowgreen areas, imparied water bodies according to Clean Water Act Section 303(d) (EPA 2015) denoted by red areas, and all HUC4 watersheds in the Missouri River Basin (1001-1030) delineated by gray polygons. The thin light-blue lines outline all streams of a Strahler order higher than 2, and the thick blue line represents the mainstem of Missouri River.}\label{fig:cropland}
\end{figure}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  How have changes in discharge (i.e.~water quantity) interacted with
  nutrient enrichment (i.e.~water quality) in the Missouri River Basin?

  \begin{enumerate}
  \def\labelenumii{\alph{enumii})}
  \tightlist
  \item
    Nutrient levels have increased over time - Keqi
  \item
    Discharge has become more variable over time - Hubert
  \item
    Nutrient levels increase with discharge - Rachel
  \end{enumerate}
\item
  What effects do specific flood and drought events have on the water
  quality and quantity of rivers in the Missouri River Basin areas of
  interest?

  \begin{enumerate}
  \def\labelenumii{\alph{enumii})}
  \tightlist
  \item
    Rivers will exhibit a flushing behavior due to the land use and type
    of flow during storms - Rachel
  \item
    Discharge will decrease during drought due to decreased overland
    flow. - Caroline
  \end{enumerate}
\item
  What factors contribute to the variability of total nitrogen in the
  rivers?

  \begin{enumerate}
  \def\labelenumii{\alph{enumii})}
  \tightlist
  \item
    Land use, year, discharge, phosphorus, and HUC region will
    contribute to the variability of total nitrogen across sites -
    Rachel
  \end{enumerate}
\item
  Given past and current data, what can we predict about the future
  state of water in the Missouri River Basin?

  \begin{enumerate}
  \def\labelenumii{\alph{enumii})}
  \tightlist
  \item
    Total flow in the Missouri River Basin is decreasing
    (non-stationary) over time - Keqi
  \item
    The future situation of the river basin will see the continuation of
    current trends of decreasing overall volume of flow. - Keqi
  \end{enumerate}
\end{enumerate}

\newpage

\hypertarget{dataset-information}{%
\section{Dataset Information}\label{dataset-information}}

The data we are analyzing comes from the United States Geological Survey
(USGS) database called the National Water Information System interface,
or NWIS. We pulled data from the interface using the R package
\texttt{dataRetrieval}. Because we are interested in the lower Missouri
River basin, we pulled sites from each HUC4 subbasin from 1020 to 1030.
We chose these subbasins because they had a variety of tributaries that
all flowed into the Missouri River, representing a variety of river
sizes and lengths. We filtered these subbasin queries to only show us
sites that contained discharge, nitrogen, and phosphorus data. Once we
found the sites with all of this data, we chose 2 sites from each HUC
sub basin for a total of 22. We chose the two sites from each HUC sub
basin by comparing the periods of records for each of our chosen
variables and finding the sites with the longest periods of records. We
chose to look at two sites per HUC region (for a total of 22) in order
to maintain a digestable scope. We retrieved data on water quantity,
water quality (N, P concentrations) (Table 1).

Only seven sites within our HUC subbasin boundary contained any high
frequency nitrogen data. Therefore, we also looked at these 6 sites in
order to do analyses and answer our research question about flooding.
Since flooding and droughts can be thought of as opposites, we looked at
the same 6 sites for droughts as we did for flooding (Table 2).

We have two main datasets:

\begin{itemize}
\item
  The daily values dataset containing discharge, nitrogen, and
  phosphorus data for 22 sites.
\item
  The high freqency dataset containing high frequency data for nitrogen
  and discharge for 6 sites.
\end{itemize}

\begin{longtable}[]{@{}lcl@{}}
\toprule
Variable & Unit & Number of Sites\tabularnewline
\midrule
\endhead
Discharge & cfs or \(m^{3}\)/s & 22\tabularnewline
Time & UTC & 22\tabularnewline
Nitrogen & mg/L & 22 with daily values, 6 with high frequency
values\tabularnewline
Phosphorus & mg/L & 22\tabularnewline
\bottomrule
\end{longtable}

Table 1: Table showing information about the dataset used for this
analysis.

\textless{}Add a table that summarizes your data structure (variables,
units, ranges and/or central tendencies, data source if multiple are
used, etc.). This table can be made in markdown text or inserted as a
\texttt{kable} function in an R chunk. If the latter, do not include the
code used to generate your table.\textgreater{}

\begin{figure}[H]
\includegraphics[width=\maxwidth]{../Figures/site_map} \caption{\label{fig:sitemap} Map of USGS sites used for long term analysis.}\label{fig:sitemap}
\end{figure}

\newpage

\hypertarget{exploratory-analysis}{%
\section{Exploratory Analysis}\label{exploratory-analysis}}

\hypertarget{exploration-of-variables}{%
\subsection{Exploration of variables}\label{exploration-of-variables}}

Basic data wrangling was needed in order to obtain all variables of
interest. After obtaining all pertinent data, each variable was
visualized in order to see the shape of the data and the range of values
(\autoref{fig:Nhist}). Any necessary transformation or cleaning was
completed after this step.

\begin{figure}[H]
\includegraphics[width=\maxwidth]{../Figures/Nitrogenhist} \caption{\label{fig:Nhist} Histograms showing the range of total nitrogen values obtained from all sites during the total period of record. Raw (left) and logged (right) nitrogen data are shown to show that any analysis requiring normally distributed data will use the log transformed nitrogen data.}\label{fig:Nhist}
\end{figure}

Discharge, nitrogen, and phosphorus were plotted for each site and
examined together in order to see if there were any obvious patterns or
trends (\autoref{fig:dataexample}).

\begin{figure}[H]
\includegraphics[width=\maxwidth]{Missouri-Reasearch-Project---FINAL_files/figure-latex/dataexample-1} \caption{\label{fig:dataexample} Discharge, Nitrogen, Phosphorus daily data of site No. 22 Missouri River At Hermann, MO.}\label{fig:dataexample}
\end{figure}

\hypertarget{yearly-discharge-pattern}{%
\subsection{Yearly Discharge Pattern}\label{yearly-discharge-pattern}}

Typical discharge patterns within a year for each HUC4 watershed from
1020 to 1030 were generated by compiling all available discharge data at
the 22 selected USGS site (\autoref{fig:dispattern}). Generally,
discharge reaches its peak during the summer and falls to minima during
the winter, and most of the sites exhibit rather high variations across
years, as indicated by the large difference between the medians and the
first or the third quartiles. Furthermore, highest variations in
discharge appear to occur in the summer, whereas discharge in the winter
varies less among years. The large variability within a year and the
seasonal pattern is only obvious in larger streams and rivers but not in
small creeks (e.g.~site 5 Maple Creek near Nickerson, site 8 Boyer
River, site 21 Small Blue River). Exceptions to the generalization are
three sites with medium discharge (site 1 Platte River, NE; site 3
Dismal River, NE; site 11 Republican River, NE). They have fairly
constant discharge and variation across years, and the the first and the
third even have slightly lower discharge during the summer. Platte River
forms by the confluence of North Platte and South Platte Rivers, and
both two have snowmelt as their water source, resulting in the observed
higher discharge during the spring and low in the summer. Dismal River
forms by two forks that arise from groundwater (Ogallala Aquifer), which
is supposed to be more stable than precipitation. The majority of
Republican River basin is underlain by Ogallala Aquifer (Reclamation
2016a), and a plausible high proportion of water source from groundwater
could explain the little variation across years.

\begin{figure}[H]
\includegraphics[width=\maxwidth]{../Figures/discharge} \caption{\label{fig:dispattern}Yearly discharge pattern for the lower Missouri HUC4 watersheds. Thick, dark lines are the median of all discharge records on a day of year, while light, thin lines are the 25th and 75 discharge quantiles on that day. The blue lines represent the first site in a HUC4 watershed, while the green lines represent the second site.}\label{fig:dispattern}
\end{figure}

\hypertarget{change-in-discharge-variations-over-years}{%
\subsection{Change in Discharge Variations over
Years}\label{change-in-discharge-variations-over-years}}

To reveal how variability of discharge has changed over time, we
analyzed the relationship between standard deviation of discharge within
a year and years, using linear models (\autoref{fig:varfig};
\autoref{tab:vartab}). Among all the 22 sites, 14 sites suggest
increasing SD over time, and 4 of them show statistically significant
increase. By contrast, only 8 sites suggest declining SD trends, and 2
of them exhibit statistically significant rising in SD. Despite that
only data from six sites (around 27\%) yield conclusive results, within
these sites the number of streams that have become more variable are two
times as many as those with decreasing variability. Thus, our results
suggest that the whole Missouri Basin appear to have become more
variable over years since around the mid-19th century. The low
percentage of significant results could result from the small effect
size, and/or the short time span of available data for some sites.
Hence, more monitoring on discharge in the basin are required in the
future to reach a more definitive conclusion.

\begin{figure}[H]
\includegraphics[width=\maxwidth]{../Figures/sd_year} \caption{\label{fig:varfig} Changes in the standard deviations (SD) of discharge within a year at 22 sites over the whole time span of available data. Red regression lines and confidence intervals suggest increasing SD, whereas blue for decreasing SD over time. Bolded site labels and HUC8, and colors with higher saturation indicate statistically significant results ($\alpha = 0.05$).}\label{fig:varfig}
\end{figure}

\begin{longtable}[]{@{}rcccc@{}}
\caption{\label{tab:vartab} Slopes of linear regression between year and
standard deviation of discharge at 22 sites.}\tabularnewline
\toprule
~ & Site Name & HUC4 & \(\beta_1\) & \emph{P}\tabularnewline
\midrule
\endfirsthead
\toprule
~ & Site Name & HUC4 & \(\beta_1\) & \emph{P}\tabularnewline
\midrule
\endhead
1 & Platte River Near Overton, NE & 1020 & -0.805 & 0.83\tabularnewline
2 & Platte River At Louisville, NE & 1020 & 33.7 & 0.144\tabularnewline
3 & Dismal River Near Thedford, NE & 1021 & 0.047 & 0.196\tabularnewline
4 & Beaver Creek At Genoa, NE & 1021 & 0.168 & 0.812\tabularnewline
5 & Maple Creek Near Nickerson, NE & 1022 & 1.1 & 0.314\tabularnewline
\textbf{6} & \textbf{Elkhorn River At Waterloo, NE} & \textbf{1022} &
\textbf{11.7} & \textbf{0.009}\tabularnewline
\textbf{7} & \textbf{Missouri River At Omaha, NE} & \textbf{1023} &
\textbf{-95.2} & \textbf{0.0093}\tabularnewline
8 & Boyer River At Logan, IA & 1023 & 2.4 & 0.134\tabularnewline
\textbf{9} & \textbf{Nishnabotna River Above Hamburg, IA} &
\textbf{1024} & \textbf{13} & \textbf{0.0018}\tabularnewline
10 & Missouri River At St.~Joseph, MO & 1024 & -32.1 &
0.452\tabularnewline
\textbf{11} & \textbf{Republican River Near Orleans, NE} & \textbf{1025}
& \textbf{-5.86} & \textbf{1e-04}\tabularnewline
12 & Republican R At Clay Center, KS & 1025 & -5.58 &
0.157\tabularnewline
13 & Smoky Hill R At Enterprise, KS & 1026 & -12.9 &
0.226\tabularnewline
14 & Sf Solomon R At Osborne, KS & 1026 & -5.27 & 0.0716\tabularnewline
15 & Kansas R At Wamego, KS & 1027 & -6.68 & 0.714\tabularnewline
16 & Kansas R At Desoto, KS & 1027 & 2.56 & 0.91\tabularnewline
\textbf{17} & \textbf{Grand River Near Sumner, MO} & \textbf{1028} &
\textbf{40.4} & \textbf{0.0264}\tabularnewline
\textbf{18} & \textbf{Chariton River Near Prairie Hill, MO} &
\textbf{1028} & \textbf{11.9} & \textbf{0.0199}\tabularnewline
19 & Pomme De Terre River Near Polk, MO & 1029 & 1.39 &
0.704\tabularnewline
20 & Osage River Below St.~Thomas, MO & 1029 & 138 &
0.311\tabularnewline
21 & Little Blue River Near Lake City, MO & 1030 & 2.1 &
0.141\tabularnewline
22 & Missouri River At Hermann, MO & 1030 & 0.657 & 0.994\tabularnewline
\bottomrule
\end{longtable}

\hypertarget{analysis}{%
\section{Analysis}\label{analysis}}

\textless{}Insert visualizations and text describing your main analyses.
Format your R chunks so that graphs are displayed but code and other
output is not displayed. Instead, describe the results of any
statistical tests in the main text (e.g., ``Variable x was significantly
different among y groups (ANOVA; df = 300, F = 5.55, p \textless{}
0.0001)''). Each paragraph, accompanied by one or more visualizations,
should describe the major findings and how they relate to the question
and hypotheses. Divide this section into subsections, one for each
research question.\textgreater{}

\textless{}Each figure should be accompanied by a caption, and each
figure should be referenced within the text\textgreater{}

\hypertarget{question-1-how-have-changes-in-discharge-interacted-with-nutrient-enrichment-in-the-missouri-river-basin}{%
\subsection{Question 1: How have changes in discharge interacted with
nutrient enrichment in the Missouri River
Basin?}\label{question-1-how-have-changes-in-discharge-interacted-with-nutrient-enrichment-in-the-missouri-river-basin}}

We analyzed discharge, nitrogen and phosphorus trends at 22 sites using
daily value data. The results are listed in the following table. In our
analysis, discharge of 18 sites increase while 4 sites show the
decreasing trend of discharge. However, these four sites all locate in
HUC 1025 and 1026, away from the main stem of the Missouri River.
Therefore, overall, the discharge in Missouri River is increasing. The
trend of nitrogen and phosphorus concentration of 22 sites are quite
different. But generally, the trend of nitrogen and the trend of
phosphorus are similar, which indicates that there is high possiblity
that nitrogen and phosphorus come from the same sources. If we focus on
the sites located at the main stem of the Missouri River (06610000
Missouri River at Omaha, NE; 06818000 Missouri River at St.~Joseph, MO;
06934500 Missouri River at Hermann, MO), we can see significant
increasing trend of nitrogen and phosphorus. The water quality in
Missouri River is still deteriorating and protection is urgently needed.

\begin{longtable}[]{@{}cccccccc@{}}
\toprule
\begin{minipage}[b]{0.06\columnwidth}\centering
Site Name\strut
\end{minipage} & \begin{minipage}[b]{0.07\columnwidth}\centering
Site Number\strut
\end{minipage} & \begin{minipage}[b]{0.08\columnwidth}\centering
Discharge Trend\strut
\end{minipage} & \begin{minipage}[b]{0.13\columnwidth}\centering
Discharge Trend Significance\strut
\end{minipage} & \begin{minipage}[b]{0.08\columnwidth}\centering
Nitrogen Trend\strut
\end{minipage} & \begin{minipage}[b]{0.16\columnwidth}\centering
Nitrogen Trend Significance\strut
\end{minipage} & \begin{minipage}[b]{0.09\columnwidth}\centering
Phosphorus Trend\strut
\end{minipage} & \begin{minipage}[b]{0.13\columnwidth}\centering
Phosphorus Trend Significance\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.06\columnwidth}\centering
Platte River near Overton, Nebr.\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\centering
06768000\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
Increase\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
Decrease\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\centering
*\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
Decrease\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering
***\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.06\columnwidth}\centering
Platte River at Louisville, Nebr.\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\centering
06805500\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
Increase\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering
***\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
Increase\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\centering
***\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
Increase\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering
***\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.06\columnwidth}\centering
Dismal River near Thedford, Nebr.\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\centering
06775900\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
Increase\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering
***\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
Decrease\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\centering
***\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
Decrease\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.06\columnwidth}\centering
Beaver Creek at Genoa, Nebr.\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\centering
06794000\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
Increase\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
Increase\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
Increase\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.06\columnwidth}\centering
Maple Creek near Nickerson, Nebr.\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\centering
06800000\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
Increase\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering
***\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
Increase\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\centering
***\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
Increase\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering
***\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.06\columnwidth}\centering
Elkhorn River at Waterloo, Nebr.\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\centering
06800500\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
Increase\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering
***\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
Increase\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\centering
*\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
Increase\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.06\columnwidth}\centering
Missouri River at Omaha, NE\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\centering
06610000\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
Increase\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering
***\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
Increase\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\centering
**\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
Increase\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering
***\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.06\columnwidth}\centering
Boyer River at Logan, IA\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\centering
06609500\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
Increase\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering
***\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
Decrease\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
Increase\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.06\columnwidth}\centering
Nishnabotna River above Hamburg, IA\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\centering
06810000\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
Increase\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering
***\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
Decrease\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
Increase\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.06\columnwidth}\centering
Missouri River at St.~Joseph, MO\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\centering
06818000\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
Increase\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering
***\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
Increase\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\centering
.\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
Increase\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.06\columnwidth}\centering
Republican River near Orleans, Nebr.\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\centering
06844500\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
Decrease\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering
***\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
Increase\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\centering
.\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
Decrease\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering
**\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.06\columnwidth}\centering
REPUBLICAN R AT CLAY CENTER, KS\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\centering
06856600\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
Decrease\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering
**\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
Decrease\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\centering
**\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
Decrease\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering
***\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.06\columnwidth}\centering
SMOKY HILL R AT ENTERPRISE, KS\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\centering
06877600\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
Decrease\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
Decrease\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\centering
.\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
Increase\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.06\columnwidth}\centering
SF SOLOMON R AT OSBORNE, KS\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\centering
06874000\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
Decrease\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering
.\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
Decrease\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\centering
***\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
Decrease\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering
***\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.06\columnwidth}\centering
KANSAS R AT WAMEGO, KS\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\centering
06887500\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
Increase\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
Increase\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\centering
***\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
Increase\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering
***\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.06\columnwidth}\centering
KANSAS R AT DESOTO, KS\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\centering
06892350\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
Increase\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering
.\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
Increase\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\centering
**\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
Increase\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering
***\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.06\columnwidth}\centering
Grand River near Sumner, MO\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\centering
06902000\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
Increase\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering
*\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
Decrease\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\centering
***\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
Increase\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.06\columnwidth}\centering
Chariton River near Prairie Hill, MO\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\centering
06905500\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
Increase\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering
*\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
Decrease\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
Increase\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.06\columnwidth}\centering
Pomme de Terre River near Polk, MO\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\centering
06921070\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
Increase\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
Decrease\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\centering
.\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
Decrease\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.06\columnwidth}\centering
Osage River below St.~Thomas, MO\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\centering
06926510\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
Increase\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
Decrease\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\centering
***\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
Increase\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering
***\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.06\columnwidth}\centering
Little Blue River near Lake City, MO\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\centering
06894000\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
Increase\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering
**\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
Decrease\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\centering
***\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
Decrease\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering
***\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.06\columnwidth}\centering
Missouri River at Hermann, MO\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\centering
06934500\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
Increase\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering
***\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
Increase\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\centering
***\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
Increase\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\centering
***\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

Note: *** p-value \textless{} 0.001 ** 0.001 \textless{}= p-value
\textless{} 0.01 * 0.01 \textless{}= p-value \textless{} 0.05 . 0.05
\textless{}= p-value \textless{} 0.1 otherwise 0.1 \textless{}= p-value
\textless{} 1

\hypertarget{question-2-what-effects-do-specific-flood-and-drought-events-have-on-the-water-quality-and-quantity-of-rivers-in-the-missouri-river-basin-areas-of-interest}{%
\subsection{Question 2: What effects do specific flood and drought
events have on the water quality and quantity of rivers in the Missouri
River Basin areas of
interest?}\label{question-2-what-effects-do-specific-flood-and-drought-events-have-on-the-water-quality-and-quantity-of-rivers-in-the-missouri-river-basin-areas-of-interest}}

\hypertarget{flooding}{%
\subsubsection{Flooding}\label{flooding}}

Population of each county (from the 2010 census) in the four states that
make up our region area of interest (Kansas, Nebraska, Missouri, and
Iowa) were found using the ``counties'' database from R's
\texttt{noncensus} package. We decided that population could be used as
a proxy for land cover, as a greater population would indicate more
development and fewer agricultural fields or open spaces.

Baseflow and quickflow from each site were determined with the
\texttt{EcoHydRology} package. After linearly interpolating the
instantaneous discharge data in order to account for gaps, total
baseflow volume was found and the percent of discharge exported as
baseflow was calculated. We predicted that a site within a county with a
large population would have a lower percent of its discharge exported as
baseflow, because quickflow would be more common in areas with a lot of
development. Similarly, we also predicted that a site within a county
with a small population would have a greater percentage of its discharge
coming from baseflow. More developed areas often have flashier floods,
and so we were curious to see whether we can relate population to an
element of flashiness - the percentage of discharge exported as
quickflow.

Contrary to our hypotheses, greater county population does not
contribute to a decrease in percent of discharge as baseflow (p =
0.4199, F = 0.8067) in our sites of interest. This may be due to our
small sample size of sites, or perhaps the size of the rivers in our
study.

High frequency nitrogen data was only available for seven sites within
our region. In order to better understand the behavior of rivers during
floods, we examined dygraph plots of discharge and nitrogen, and created
hysteresis plots. Storms from the fall of 2018 (September - December)
were examined for each river site with data from that time period. We
chose to only look at storms that occurred in the second half of the
year in order to avoid conflating snowpack melt and precipitation
affects.

We predicted that most rivers in the area would behave the same way, and
that rivers would exhibit flushing behavior. We thought that flushing
rivers would be more prevalent because of the many agricultural fields
in our region of study, and any overland flow to the rivers would bring
with it a high concentration of nutrients (nitrogen being one of them)
from the fertilized fields. Our results say otherwise (Table 2). Our
sites of interest had both positive and negative slopes in the
hysteresis plots, and also exhibited both clockwise and counter
clockwise directions of flow (\autoref{fig:RandolphStorm}). The same
river was analyzed multiple times throughout the year, and even the same
river showed different slopes and directions in the hysteresis plots for
different storm events.

\begin{longtable}[]{@{}lclll@{}}
\toprule
\begin{minipage}[b]{0.15\columnwidth}\raggedright
Site Name\strut
\end{minipage} & \begin{minipage}[b]{0.22\columnwidth}\centering
Site Number\strut
\end{minipage} & \begin{minipage}[b]{0.20\columnwidth}\raggedright
Time Period\strut
\end{minipage} & \begin{minipage}[b]{0.17\columnwidth}\raggedright
Direction\strut
\end{minipage} & \begin{minipage}[b]{0.12\columnwidth}\raggedright
Slope\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.15\columnwidth}\raggedright
West Nishnabotna River in Randolph, IA\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\centering
06808500\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedright
Oct 7 - 13, 2018\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedright
counter clockwise\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
negative (Figure xx)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.15\columnwidth}\raggedright
Nodaway River at Clarinda, IA\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\centering
06817000\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedright
Oct 8 - 12, 2018\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedright
clockwise\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
negative\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.15\columnwidth}\raggedright
Kansas River in Desoto, KS\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\centering
06892350\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedright
Nov 30 - Dec 5, 2018\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedright
counter clockwise\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
positive\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.15\columnwidth}\raggedright
Missouri River at Hermann, MO\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\centering
06934500\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedright
Oct 7 - 20, 2018\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedright
counter clockwise\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
negative\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.15\columnwidth}\raggedright
Mill C at Johnson Drive, Shawnee, KS\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\centering
06892513\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedright
Nov 27 - Dec 4, 2018\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedright
clockwise\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
negative\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.15\columnwidth}\raggedright
Grand River, Sumner MO\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\centering
06902000\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedright
Sep 6 - 10, 2018\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedright
clockwise\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
positive\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\begin{figure}
\centering
\includegraphics{Missouri-Reasearch-Project---FINAL_files/figure-latex/Randolphstorm-1.pdf}
\caption{Hyteresis plot for site in Randolph, IA that shows a negative
slope (diluting behavior) in a counter clockwise direction.}
\end{figure}

\hypertarget{droughts}{%
\subsubsection{Droughts}\label{droughts}}

Droughts in the Missouri River Basin were known to occur throughout the
years and six sites were analyzed for drought information. The six sites
were chosen based off what was examined for floods.

Drought was defined as determining the 7Q10, which is the minimum 7-day
average flow that will occur every 10 years (probability of 10\%) (EPA,
2019). The 7Q10 measurement is used to determine streamflow limits,
allocate water resources, dilution rates in watersheds, and more (USGS,
2019). 7Q10 is calculated by determining the recurrence interval, which
is the past recurrence of an event, which for droughts would be the
minimum 7-day average discharge. The recurrence interval can then be
used to calculate the probability, which would be the probability or
likelihood of having a minimum 7-day average flow of this magnitude or
greater. In this case, the minimum 7-day average flow that has a 10\%
chance of going below that value in a given year.

The recurrence interval is calculated using the following equation:

\(T = (n+1)/m\)

where T is the recurrence interval, n is the number of years of data,
and m is the ranking of the event within the years of data.

Exceedance probability is calculated to determine the probability of
having a discharge event of a given size or greater in a year. The
equation is:

\(P = 1/T\)

where P is the exceedance probability, and T is the recurrence interval.

The 7Q10 was calculated for each of the six sites by first filtering the
discharge data to only include the selected site. The `rollmean'
function was then used to calculate the average flow every 7 days for
said site. Once the 7-day average flow was calculated, the data was
grouped by the year so that it could then be summarized to obtain the
minimum 7-day average flow. After grouping and summarizing the data,
there was one value, the minimum 7-day average flow, for each year of
data obtained. From here, the recurrence interval and probability were
calculated in each data frame.

The 7Q10 value was then determined from the probability column by
filtering the data to show the minimum 7-day average discharge with
probability less than or equal to 0.1 (Table 3).

Table summarizing the 7Q10 values for each of the streams that were
analyzed for droughts.

\begin{longtable}[]{@{}lll@{}}
\toprule
Site Name & Site Number & 7Q10 Minimum Discharge (cfs)\tabularnewline
\midrule
\endhead
West Nishnabotna River in Randolph, IA & 06808500 & 41.3\tabularnewline
Nodaway River at Clarinda, IA & 06817000 & 5.93\tabularnewline
Kansas River in Desoto, KS & 06892350 & 562\tabularnewline
Missouri River at Hermann, MO & 06934500 & 12414\tabularnewline
Mill C at Johnson Drive, Shawnee, KS & 06892513 & 1.47\tabularnewline
Grand River, Sumner MO & 06902000 & 39.1\tabularnewline
\bottomrule
\end{longtable}

In addition to calculating the 7Q10 values for the 6 sites, the sites
were analyzed to determine the 7-day moving average flow over a period
of years. The 25th, 50th, and 75th quantiles were calculated to
determine the minimum, median, and maximum values for discharge in a
given year. The 7-day moving average flow over a period of years was
then plotted with the 25th, 50th, and 75th quantiles representing normal
drought conditions, drought watch, drought warning, and drought
emergency (Figure \_\_\_\_). This information about what flow would
constitute a drought is extremely useful for water managers.

\hypertarget{question-3-what-factors-contribute-to-the-variability-of-total-nitrogen-in-the-rivers}{%
\subsection{Question 3: What factors contribute to the variability of
total nitrogen in the
rivers?}\label{question-3-what-factors-contribute-to-the-variability-of-total-nitrogen-in-the-rivers}}

In order to better understand what contributes to the variability of
nitrogen concentration in our study area of interest, we created a
linear model with fixed effects and random effects. By considering the
HUC 4 region each site is in as a random effect, we can estimate the
amount of variation of nitrogen between each HUC 4. In order to better
model the interaction, I chose to divide the year variable by 10 and the
population by 1000 so that rescaling is not an issue. The model chosen
is below:

\begin{quote}
\texttt{lmer(data,\ log(total.nitrogen)\ \textasciitilde{}\ Year\ +\ population\ \ +\ (1\textbar{}huc4))}
\end{quote}

Year and population are fixed effects while the grouping of the HUC 4
region is a random effect. This means we take the HUC 4 region variance
into account when modeling the effect of year and population on total
nitrogen. Using log transformed nitrogen data and HUC 4 region as a
random effect, there is a significant difference in total nitrogen
across each decade and every 1000 people (p \textless{} 2e-16). The
regression equation is below:

\[log(Total Nitrogen) = -3.68 + 0.0229(Year/10) - 9.95e-04(population/1000)\]

Because we used a log transformed data set, we have to exponentiate the
coefficients in the model to interpret them. The intercept is 0.025,
which is the mean of total nitrogen when year is 0 and population is 0.
When exponentiating the Year coefficient, we can conclude that every
decade has a 1.02 multiplicative effect on nitrogen. When exponentiating
the population coefficient, we can conclude that every 1000 people have
a 0.99 multiplicative effect on nitrogen. The model demonstrates the the
level of decade and population affected the total nitrogen in each HUC 4
region. Residuals are evenly distributed, and the R\^{}2 value = 0.514,
indicating that 51.4\% of the variation in nitrogen is explained by this
model.

\hypertarget{question-4-given-past-and-current-data-what-can-we-predict-about-the-future-state-of-water-in-the-missouri-river-basin}{%
\subsection{Question 4: Given past and current data, what can we predict
about the future state of water in the Missouri River
Basin?}\label{question-4-given-past-and-current-data-what-can-we-predict-about-the-future-state-of-water-in-the-missouri-river-basin}}

\begin{longtable}[]{@{}cccccccccccccc@{}}
\toprule
\begin{minipage}[b]{0.05\columnwidth}\centering
Site Name\strut
\end{minipage} & \begin{minipage}[b]{0.06\columnwidth}\centering
Site Number\strut
\end{minipage} & \begin{minipage}[b]{0.05\columnwidth}\centering
Dec.~2019\strut
\end{minipage} & \begin{minipage}[b]{0.04\columnwidth}\centering
Jan.~2020\strut
\end{minipage} & \begin{minipage}[b]{0.05\columnwidth}\centering
Feb.~2020\strut
\end{minipage} & \begin{minipage}[b]{0.05\columnwidth}\centering
Mar.~2020\strut
\end{minipage} & \begin{minipage}[b]{0.05\columnwidth}\centering
Apr.~2020\strut
\end{minipage} & \begin{minipage}[b]{0.04\columnwidth}\centering
May 2020\strut
\end{minipage} & \begin{minipage}[b]{0.05\columnwidth}\centering
June 2020\strut
\end{minipage} & \begin{minipage}[b]{0.05\columnwidth}\centering
July 2020\strut
\end{minipage} & \begin{minipage}[b]{0.05\columnwidth}\centering
Aug.~2020\strut
\end{minipage} & \begin{minipage}[b]{0.05\columnwidth}\centering
Sept.~2020\strut
\end{minipage} & \begin{minipage}[b]{0.04\columnwidth}\centering
Oct.~2020\strut
\end{minipage} & \begin{minipage}[b]{0.04\columnwidth}\centering
Nov.~2020\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.05\columnwidth}\centering
Platte River near Overton, Nebr.\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering
06768000\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
2019.992\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
1942.129\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
1929.816\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
2040.176\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
2032.186\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
1990.873\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
2023.824\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
2008.55\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
1928.585\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
1996.895\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
1979.38\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
2026.699\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.05\columnwidth}\centering
Platte River at Louisville, Nebr.\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering
06805500\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
14060.7\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
12802.25\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
12845.87\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
23729.49\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
15056.78\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
16585.16\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
18430.86\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
15168.09\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
15216.99\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
14719.46\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
13635.78\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
12780.16\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.05\columnwidth}\centering
Dismal River near Thedford, Nebr.\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering
06775900\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
239.2089\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
238.9801\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
238.3116\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
239.5916\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
240.5232\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
242.5456\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
242.0369\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
241.6409\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
242.0486\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
242.2389\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
241.9548\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
240.2764\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.05\columnwidth}\centering
Beaver Creek at Genoa, Nebr.\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering
06794000\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
148.0349\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
129.4563\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
129.6965\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
327.3795\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
165.0577\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
190.15\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
189.022\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
172.7318\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
157.0474\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
146.7917\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
151.0374\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
136.0562\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.05\columnwidth}\centering
Maple Creek near Nickerson, Nebr.\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering
06800000\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
173.1581\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
150.6924\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
141.7451\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
313.545\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
159.0779\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
199.5598\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
187.1167\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
149.6114\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
148.6135\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
149.6721\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
146.2639\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
136.3859\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.05\columnwidth}\centering
Elkhorn River at Waterloo, Nebr.\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering
06800500\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
2607.337\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
2598.611\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
2672.196\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
3208.066\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
3341.665\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
3977.717\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
3785.948\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
2912.286\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
2434.121\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
3091.355\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
2733.932\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
2520.393\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.05\columnwidth}\centering
Missouri River at Omaha, NE\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering
06610000\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
70976.66\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
60591.76\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
55874.04\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
73723.59\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
81113.53\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
83595.71\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
90800.91\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
85219.7\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
78593.88\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
80467.92\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
78227.7\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
70854.33\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.05\columnwidth}\centering
Boyer River at Logan, IA\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering
06609500\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
708.6843\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
691.4817\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
645.5966\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
1176.8041\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
714.8702\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
814.9989\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
800.516\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
733.6069\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
650.3337\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
655.3034\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
724.2999\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
689.9273\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.05\columnwidth}\centering
Nishnabotna River above Hamburg, IA\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering
06810000\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
2422.32\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
2391.721\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
2377.854\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
3204.073\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
2417.139\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
2731.861\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
3004.86\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
2650.792\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
2460.292\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
2777.403\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
3156.369\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
2595.649\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.05\columnwidth}\centering
Missouri River at St.~Joseph, MO\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering
06818000\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
90011.3\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
77760.16\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
70549.03\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
116938.26\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
110927.07\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
130362.46\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
131671.16\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
110560.74\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
99105.45\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
103960.49\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
121688.94\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
96803.96\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.05\columnwidth}\centering
Republican River near Orleans, Nebr.\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering
06844500\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
154.9544\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
145.2851\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
147.9408\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
228.2876\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
171.8784\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
166.0301\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
184.0507\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
321.3987\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
164.3744\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
150.4602\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
149.7053\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
158.701\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.05\columnwidth}\centering
REPUBLICAN R AT CLAY CENTER, KS\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering
06856600\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
2212.686\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
2012.946\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
1966.35\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
2354.776\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
2052.399\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
2615.569\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
2571.786\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
2483.559\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
2404.832\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
2283.906\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
2196.924\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
2058.036\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.05\columnwidth}\centering
SMOKY HILL R AT ENTERPRISE, KS\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering
06877600\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
1999.598\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
1814.097\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
1688.58\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
1807.765\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
1634.919\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
2308.793\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
2034.465\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
1885.749\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
1831.551\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
1777.794\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
1663.053\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
1556.348\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.05\columnwidth}\centering
SF SOLOMON R AT OSBORNE, KS\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering
06874000\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
174.3205\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
140.6582\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
123.4546\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
114.6624\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
110.1691\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
107.8727\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
106.6991\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
106.0993\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
105.7928\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
105.6361\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
105.556\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
105.5151\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.05\columnwidth}\centering
KANSAS R AT WAMEGO, KS\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering
06887500\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
14398.77\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
10484.501\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
7784.95\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
6938.432\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
5800.966\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
7571.298\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
8326.411\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
9052.989\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
6796.397\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
6676.547\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
6316.088\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
7646.2\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.05\columnwidth}\centering
KANSAS R AT DESOTO, KS\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering
06892350\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
17433.744\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
13064.978\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
10272.795\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
9334.909\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
7730.841\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
11531.101\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
11710.275\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
12100.027\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
10099.463\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
9499.502\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
8509.621\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
9945.916\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.05\columnwidth}\centering
Grand River near Sumner, MO\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering
06902000\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
9634.729\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
9456.489\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
10440.135\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
10753.103\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
9392.489\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
12326.771\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
11756.818\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
9390.933\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
9517.493\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
10274.174\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
12340.875\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
9446.777\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.05\columnwidth}\centering
Chariton River near Prairie Hill, MO\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering
06905500\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
1946.371\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
2523.677\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
2663.863\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
2701.267\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
2556.851\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
3142.349\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
2904.042\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
2597.213\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
2511.393\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
2678.037\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
2898.101\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
2629.494\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.05\columnwidth}\centering
Pomme de Terre River near Polk, MO\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering
06921070\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
302.1977\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
290.1968\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
335.3464\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
317.8665\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
267.6631\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
404.104\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
262.339\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
255.1629\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
247.3837\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
250.4061\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
269.6108\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
277.8386\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.05\columnwidth}\centering
Osage River below St.~Thomas, MO\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering
06926510\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
12184.39\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
13730.31\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
13039.62\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
12564.56\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
14026.34\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
14174.23\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
16191.64\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
16801.49\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
15671.6\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
14122.26\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
13155.48\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
12236.42\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.05\columnwidth}\centering
Little Blue River near Lake City, MO\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering
06894000\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
181.6666\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
206.4976\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
203.7249\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
206.7256\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
214.5459\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
320.4555\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
220.6817\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
228.4371\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
209.8449\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
231.759\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
198.792\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
190.647\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.05\columnwidth}\centering
Missouri River at Hermann, MO\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering
06934500\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
189461.2\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
194893.2\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
194212.8\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
215398.5\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
212735.9\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
230589.3\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
240828.8\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
227848.5\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
213285.9\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering
216789.6\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
230480\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\centering
210515\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\newpage

\hypertarget{summary-and-conclusions}{%
\section{Summary and Conclusions}\label{summary-and-conclusions}}

\textless{}Summarize your major findings from your analyses in a few
paragraphs. What conclusions do you draw from your findings? Relate your
findings back to the original research questions and
rationale.\textgreater{}

\newpage

\hypertarget{references}{%
\section*{References}\label{references}}
\addcontentsline{toc}{section}{References}

\hypertarget{refs}{}
\leavevmode\hypertarget{ref-nrc2002}{}%
Council, National Research. 2002. \emph{The Missouri River Ecosystem:
Exploring the Prospects for Recovery}. Book. Washington, DC: The
National Academies Press. \url{https://doi.org/doi:10.17226/10277}.

\leavevmode\hypertarget{ref-usace2018}{}%
Engineers Missouri River Basin Water Management Division, U.S. Army
Corps of. 2018. ``Master Water Control Manual Missouri River Basin.''
Government Document.

\leavevmode\hypertarget{ref-noaa2013}{}%
Force, NOAA Drought Task. 2013. ``An Interpretation of the Origins of
the 2012 Central Great Plains Drought.'' Government Document.
\url{https://cpo.noaa.gov/Meet-the-Divisions/Earth-System-Science-and-Modeling/MAPP/MAPP-Task-Forces/Drought/Drought-Task-Force-II/An-Interpretation-of-the-Origins-of-the-2012-Central-Great-Plains-Drought}.

\leavevmode\hypertarget{ref-kammerer1990}{}%
Kammerer, J.C. 1990. ``Largest Rivers in the United States.'' Report.
U.S. Geological Survey, Department of the Interior.

\leavevmode\hypertarget{ref-noaa2012}{}%
Oceanic, National, and Atmospheric Administration. 2012. ``Service
Assessment the Missouri/Souris River Floods of May -- August 2011.''
Government Document.

\leavevmode\hypertarget{ref-bor2016-2}{}%
Reclamation, Bureau of. 2016a. ``Republican River Basin Study.''
Government Document.
\url{https://www.usbr.gov/watersmart/bsp/docs/finalreport/republican/republican-river-basin-study-final-report.pdf}.

\leavevmode\hypertarget{ref-bor2016-1}{}%
---------. 2016b. ``SECURE Water Act Section 9503(c) Report to
Congress.'' Report.
\url{https://www.usbr.gov/climate/secure/docs/2016secure/2016SECUREReport-chapter6.pdf}.


\end{document}
